/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppAuditRouteImport } from './routes/_app.audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AppAuditRoute
  '/inventory': typeof AppInventoryRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/audit': typeof AppAuditRoute
  '/inventory': typeof AppInventoryRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/inventory'
    | '/pos'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/audit'
    | '/inventory'
    | '/pos'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/audit'
    | '/_app/inventory'
    | '/_app/pos'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/users'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
